server:
  .port: 8082

spring:
  application:
    name: HotelApp

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka